CREATE TABLE yinzdata (
YID INT NOT NULL AUTO_INCREMENT,
hardware_manufacturer VARCHAR(255),
hardware_model VARCHAR(255),
hardware_platform VARCHAR(255),
hardware_screen_width INT,
hardware_screen_height INT,
device_id VARCHAR(255),
device_os_version VARCHAR(255),
device_mcc INT,
device_mnc INT,
device_carrier VARCHAR(255),
session_id VARCHAR(255),
session_start_date_time TIMESTAMP,
session_end_date_time TIMESTAMP,
action_mysql_id INT,
action_type_major VARCHAR(255),
action_type_minor VARCHAR(255),
action_resource_major VARCHAR(255),
action_resource_minor INT,
action_request_time TIMESTAMP,
action_invisible_time TIMESTAMP,
action_sort_order INT,
geoip_continent_code VARCHAR(255),
geoip_country_code VARCHAR(255),
geoip_time_zone VARCHAR(255),
PRIMARY KEY (YID)
);